# LOGISTIC REGRESSION -  acc = 49.2

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('TURNOVER.csv')
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
y_pred = classifier.predict(X_test)

In [9]:
print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 227981
SIZE OF TESTING DATASET==> 57000
SHAPE OF TRAINING DATASET==> (11999, 19)
SHAPE OF TESTING DATASET==> (3000, 19)


In [10]:
from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(y_test, y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(
    Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[  41  158   58]
 [  15 1107  329]
 [  47  917  328]]
Accuracy in %=  49.2


In [11]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(y_pred)
print("Accuracy values for the turnover classes = ",Accuracy)

Model Evaluation Metrics
Total Observations predicted 3000
True Positive=> [  41 1107  328]
True Negative=> [2681  474 1321]
False Positive=> [  62 1075  387]
False Negatives=> [216 344 964]
Accuracy values for the turnover classes =  [0.90733333 0.527      0.54966667]


# KNN -  acc = 50.6

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
dataset = pd.read_csv('TURNOVER.csv')
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 227981
SIZE OF TESTING DATASET==> 57000
SHAPE OF TRAINING DATASET==> (11999, 19)
SHAPE OF TESTING DATASET==> (3000, 19)


In [21]:
from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(y_test, y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(
    Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[ 39 131  87]
 [ 70 900 481]
 [ 73 640 579]]
Accuracy in %=  50.6


In [22]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(y_pred)
print("Accuracy values for the turnover classes = ",Accuracy)

Model Evaluation Metrics
Total Observations predicted 3000
True Positive=> [ 39 900 579]
True Negative=> [2600  778 1140]
False Positive=> [143 771 568]
False Negatives=> [218 551 713]
Accuracy values for the turnover classes =  [0.87966667 0.55933333 0.573     ]


# NAIVE BAYES -  acc = 46.86

In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
dataset = pd.read_csv('TURNOVER.csv')
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [25]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [26]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [30]:
y_pred = classifier.predict(X_test)

In [31]:
print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 227981
SIZE OF TESTING DATASET==> 57000
SHAPE OF TRAINING DATASET==> (11999, 19)
SHAPE OF TESTING DATASET==> (3000, 19)


In [32]:
from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(y_test, y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(
    Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[  53  182   22]
 [  63 1217  171]
 [ 136 1020  136]]
Accuracy in %=  46.86666666666667


In [33]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(y_pred)
print("Accuracy values for the turnover classes = ",Accuracy)

Model Evaluation Metrics
Total Observations predicted 3000
True Positive=> [  53 1217  136]
True Negative=> [2544  347 1515]
False Positive=> [ 199 1202  193]
False Negatives=> [ 204  234 1156]
Accuracy values for the turnover classes =  [0.86566667 0.52133333 0.55033333]


# SVM -  acc = 51.46

In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
dataset = pd.read_csv('TURNOVER.csv')
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [36]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [37]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 227981
SIZE OF TESTING DATASET==> 57000
SHAPE OF TRAINING DATASET==> (11999, 19)
SHAPE OF TESTING DATASET==> (3000, 19)


In [43]:
from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(y_test, y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(
    Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[  22  161   74]
 [  11 1117  323]
 [  22  865  405]]
Accuracy in %=  51.46666666666667


In [44]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(y_pred)
print("Accuracy values for the turnover classes = ",Accuracy)

Model Evaluation Metrics
Total Observations predicted 3000
True Positive=> [  22 1117  405]
True Negative=> [2710  523 1311]
False Positive=> [  33 1026  397]
False Negatives=> [235 334 887]
Accuracy values for the turnover classes =  [0.91066667 0.54666667 0.572     ]


# DECISION TREE CLASSIFICATION -  acc = 60.63

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [46]:
dataset = pd.read_csv('TURNOVER.csv')
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [47]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [48]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [51]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [52]:
y_pred = classifier.predict(X_test)

In [53]:
print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 227981
SIZE OF TESTING DATASET==> 57000
SHAPE OF TRAINING DATASET==> (11999, 19)
SHAPE OF TESTING DATASET==> (3000, 19)


In [54]:
from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(y_test, y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(
    Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[ 96  68  93]
 [ 88 927 436]
 [ 75 421 796]]
Accuracy in %=  60.633333333333326


In [55]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(y_pred)
print("Accuracy values for the turnover classes = ",Accuracy)

Model Evaluation Metrics
Total Observations predicted 3000
True Positive=> [ 96 927 796]
True Negative=> [2580 1060 1179]
False Positive=> [163 489 529]
False Negatives=> [161 524 496]
Accuracy values for the turnover classes =  [0.892      0.66233333 0.65833333]


# RANDOM FOREST CLASSIFICATION -  acc = 62.53

In [56]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [57]:
dataset = pd.read_csv('TURNOVER.csv')
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [58]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [59]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [61]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [62]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [63]:
y_pred = classifier.predict(X_test)

In [64]:
print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 227981
SIZE OF TESTING DATASET==> 57000
SHAPE OF TRAINING DATASET==> (11999, 19)
SHAPE OF TESTING DATASET==> (3000, 19)


In [65]:
from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(y_test, y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(
    Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[  86   88   83]
 [  21 1069  361]
 [  35  536  721]]
Accuracy in %=  62.53333333333333


In [66]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(y_pred)
print("Accuracy values for the turnover classes = ",Accuracy)

Model Evaluation Metrics
Total Observations predicted 3000
True Positive=> [  86 1069  721]
True Negative=> [2687  925 1264]
False Positive=> [ 56 624 444]
False Negatives=> [171 382 571]
Accuracy values for the turnover classes =  [0.92433333 0.66466667 0.66166667]


# LINEAR REGRESSION

In [67]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [68]:
dataset = pd.read_csv('TURNOVER.csv')
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [69]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [70]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [72]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

ValueError: could not convert string to float: 'medium'