In [1152]:
import numpy as np
import random
import pandas as pd

In [1153]:
entity_id=list(range(50000))
city_type = ["A","B","C","D"]
gender = ["male","female"]
marital_status = ["married","unmarried"]
education = ["Ph.d","PG","UG","Not educated"]

#Defining the column which do not take specific values 
#creating list of random integer in the given range 
Dependents=list(range(5))
EntityIncome =list(range(10000,400000,10000))
#For EntityFamilyIncome column if the number of dependents are 0 then the Entityfamilyincome == Entiyincome this case is taken care of.
#Entityfamilyincome  column is defined later in the code

In [1154]:
#METHOD OF GENERATING THE DATASET

#If coin flip=1(tail) if coin flip=0(head)
# Rolling the dice if head comes.
#Generating random integer in between 0 and (number of options for given feature -1) 
# meaning the number of options a feature can take
#this process is done for all the columns except for Average Expenditure per Entity per Month column
#As the ques expect us to follow other appproach for generation of that column

In [1155]:
Dependents_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)   #If coin flip=1(tail) if coin flip=0(head)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(Dependents)-1) # Rolling the dice if head comes.
        Dependents_vec.append(Dependents[dice_roll])
    else:
        Dependents_vec.append(2)

In [1156]:
marital_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)     #If coin flip=1(tail) if coin flip=0(head)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(marital_status)-1)# Rolling the dice if head comes.
        marital_vec.append(marital_status[dice_roll])
    else:
        marital_vec.append("married")

In [1157]:
city_type_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)   #If coin flip=1(tail) if coin flip=0(head)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(city_type)-1)# Rolling the dice if head comes.
        city_type_vec.append(city_type[dice_roll])
    else:
        city_type_vec.append("C")

In [1158]:
gender_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)  #If coin flip=1(head) if coin flip=0(tail)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(gender)-1)# Rolling the dice if head comes.
        gender_vec.append(gender[dice_roll])
    else:
        gender_vec.append("female")

In [1159]:
education_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)  #If coin flip=1(head) if coin flip=0(tail)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(education)-1)# Rolling the dice if head comes.
        education_vec.append(education[dice_roll])
    else:
        education_vec.append("UG")

In [1160]:
entity_income_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)   #If coin flip=1(head) if coin flip=0(tail)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(EntityIncome)-1)# Rolling the dice if head comes.
        entity_income_vec.append(EntityIncome[dice_roll])
    else:
        entity_income_vec.append("10000")

In [1161]:
avg_exp_vec=[]
for i in range(50000):
        if(city_type_vec[i]== "A"):
            avg_exp_vec.append(15000)
        elif (city_type_vec[i]=="D"):
            avg_exp_vec.append(2500)
        elif (city_type_vec[i]=="C"):
            avg_exp_vec.append(5000)
        else:
            avg_exp_vec.append(10000)
        

In [1162]:
entity_family_income_vec=[]

for i in range(50000):
    if(Dependents_vec[i]>0):
        entity_family_income_vec.append(random.randint(10000,100000))
    else:
        entity_family_income_vec.append(entity_income_vec[i])

In [1163]:
total_income_vec=[]

for i in range(50000):
    j=random.randint(0,1)
    income=(int(entity_income_vec[i])+int(entity_family_income_vec[i]))
    total_income_vec.append(income)

In [1164]:
savings_vec=[]
for i in range(50000):
    savings=(int(total_income_vec[i])-int(avg_exp_vec[i]))
    savings_vec.append(savings)

In [1165]:
car_loan_vec=[]
for i in range(50000):
    if (int(savings_vec[i] > 50000)):
            car_loan_vec.append("Yes")
    else:       
            car_loan_vec.append("No")

In [1166]:
house_loan_vec=[]
for i in range(50000):
    if (int(savings_vec[i] > 100000)):
            house_loan_vec.append("Yes")
    else:       
            house_loan_vec.append("No")

In [1167]:
economic_status_vec=[]   
economic_status_label_vec=[]
for i in range(50000):
    if(savings_vec[i] >=300000):
            economic_status_vec.append("Excellent")
            economic_status_label_vec.append(0)
    elif(savings_vec[i] >200000 and savings_vec[i] < 300000 ):
            economic_status_vec.append("Good")
            economic_status_label_vec.append(1)
    elif(savings_vec[i] > 100000 and savings_vec[i] <= 200000):
            economic_status_vec.append("Moderate")
            economic_status_label_vec.append(2)
    elif(savings_vec[i] >50000 and savings_vec[i] <= 100000):
            economic_status_vec.append("Average")    
            economic_status_label_vec.append(3)
    else:
            economic_status_vec.append("Poor") 
            economic_status_label_vec.append(4)

In [1168]:
DataSet = pd.DataFrame()
DataSet["Entity_ID"] = entity_id
DataSet["City"] = city_type_vec
DataSet["Marital Status"] = marital_vec
DataSet["Education"] = education_vec
DataSet["Gender"] =gender_vec
DataSet["Dependencies"]=Dependents_vec
DataSet["Entity's Income"]=entity_income_vec
DataSet["Entity's Family Income"]= entity_family_income_vec
DataSet["Average Expenditure per Entity per Month"]= avg_exp_vec
DataSet["Total Income of Entity's Family"] = total_income_vec
DataSet["Savings"]=savings_vec
DataSet["Car_Loan"] =car_loan_vec
DataSet["House_Loan"] =house_loan_vec
DataSet["Family Status"]= economic_status_vec
DataSet["Family_Status_Label"]=economic_status_label_vec
DataSet

Entity_ID City Marital Status     Education  Gender  Dependencies  \
0              0    C        married          Ph.d    male             4   
1              1    C      unmarried            UG    male             1   
2              2    C        married            UG    male             1   
3              3    C        married            UG  female             3   
4              4    C        married            PG  female             2   
5              5    B        married            UG    male             0   
6              6    C        married            UG  female             2   
7              7    B        married            UG    male             2   
8              8    C        married            UG  female             2   
9              9    C        married            UG  female             2   
10            10    C        married            UG  female             2   
11            11    C        married            UG    male             2   
12            12    A      unmarried            UG    male             0   
13            13    C        married          Ph.d  female             2   
14            14    C        married            UG  female             4   
15            15    C        married          Ph.d  female             2   
16            16    D        married            UG    male             1   
17            17    B        married            PG  female             0   
18            18    D        married          Ph.d  female             2   
19            19    C        married            UG  female             2   
20            20    C        married            UG    male             3   
21            21    D        married            UG  female             3   
22            22    C        married          Ph.d  female             3   
23            23    C        married            UG  female             2   
24            24    C        married            PG  female             0   
25            25    C        married            UG  female             0   
26            26    C        married            UG  female             2   
27            27    A        married  Not educated  female             4   
28            28    C      unmarried            UG    male             4   
29            29    C        married            UG  female             2   
...          ...  ...            ...           ...     ...           ...   
49970      49970    C        married            PG  female             4   
49971      49971    C        married            UG  female             2   
49972      49972    A      unmarried            UG  female             2   
49973      49973    C      unmarried            PG  female             2   
49974      49974    C        married            UG  female             1   
49975      49975    C        married            UG  female             4   
49976      49976    C        married            UG    male             2   
49977      49977    C        married            PG  female             1   
49978      49978    C        married            UG    male             2   
49979      49979    C      unmarried            UG  female             1   
49980      49980    B        married            UG  female             2   
49981      49981    C        married            UG    male             2   
49982      49982    C        married          Ph.d  female             2   
49983      49983    B        married  Not educated  female             4   
49984      49984    C        married            UG    male             2   
49985      49985    C        married            UG  female             2   
49986      49986    B      unmarried  Not educated  female             2   
49987      49987    C      unmarried            UG  female             2   
49988      49988    A        married            UG    male             2   
49989      49989    C        married            UG  female             2   
49990      49990    A      unmarried            UG  fem

In [1169]:
temp=DataSet
# Import LabelEncoder
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X=["City","Marital Status","Education","Gender","Dependencies","Entity\'s Income","Entity\'s Family Income","Average Expenditure per Entity per Month","Total Income of Entity\'s Family","Savings","Car_Loan","House_Loan"]
Y=["Family_Status_Label"]


le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
temp['Average Expenditure per Entity per Month']=le.fit_transform(temp['Average Expenditure per Entity per Month'])
temp['Gender']=le.fit_transform(temp['Gender'])
temp['Education']=le.fit_transform(temp['Education'])
temp['Marital Status']=le.fit_transform(temp['Marital Status'])
temp['City']=le.fit_transform(temp['City'])
temp['Car_Loan'] = le.fit_transform(temp['Car_Loan'])
temp['House_Loan'] = le.fit_transform(temp['House_Loan'])

X=temp[X]
Y=temp[Y]

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)


# instantiate the model 
Log_Regression = LogisticRegression(C=10, solver='newton-cg', multi_class='multinomial')

# fit the model with data
Log_Regression.fit(X_train,Y_train)
Y_pred=Log_Regression.predict(X_test)


C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [1170]:
print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 480000
SIZE OF TESTING DATASET==> 120000
SHAPE OF TRAINING DATASET==> (40000, 12)
SHAPE OF TESTING DATASET==> (10000, 12)


In [1171]:
from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(Y_test, Y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[1907   60    0    0    0]
 [  84 1107   55    0    0]
 [   0   78 1327    0    0]
 [   0    0    0 2926    0]
 [   0    0    0    0 2456]]
Accuracy in %=  97.23


In [1172]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(Y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(Y_pred)
print("Accuracy values for the 5 economic classes = ",Accuracy)

Model Evaluation Metrics
Total Observations predicted 10000
True Positive=> [1907 1107 1327 2926 2456]
True Negative=> [7949 8616 8540 7074 7544]
False Positive=> [ 84 138  55   0   0]
False Negatives=> [ 60 139  78   0   0]
Accuracy values for the 5 economic classes =  [0.9856 0.9723 0.9867 1.     1.    ]
