In [1]:
import numpy as np
import random
import pandas as pd

In [2]:
#Defining the column which takes categorical values
entity_id=list(range(50000))
city_type = ["A","B","C","D"]
gender = ["male","female"]
marital_status = ["married","unmarried"]
education = ["Ph.d","PG","UG","Not educated"]

#Defining the column which do not take specific values 
#creating list of random integer in the given range 
Dependents=list(range(5))
EntityIncome =list(range(10000,2000000,10000))
#For EntityFamilyIncome column if the number of dependents are 0 then the Entityfamilyincome == Entiyincome this case is taken care of.
#Entityfamilyincome  column is defined later in the code

In [3]:
#METHOD OF GENERATING THE DATASET

#If coin flip=1(tail) if coin flip=0(head)
# Rolling the dice if head comes.
#Generating random integer in between 0 and (number of options for given feature -1) 
# meaning the number of options a feature can take
#this process is done for all the columns except for Average Expenditure per Entity per Month column
#As the ques expect us to follow other appproach for generation of that column

In [4]:
Dependents_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)   #If coin flip=1(tail) if coin flip=0(head)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(Dependents)-1) # Rolling the dice if head comes.
        Dependents_vec.append(Dependents[dice_roll])
    else:
        Dependents_vec.append(2)

In [5]:
marital_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)     #If coin flip=1(tail) if coin flip=0(head)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(marital_status)-1)# Rolling the dice if head comes.
        marital_vec.append(marital_status[dice_roll])
    else:
        marital_vec.append("married")

In [6]:
city_type_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)   #If coin flip=1(tail) if coin flip=0(head)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(city_type)-1)# Rolling the dice if head comes.
        city_type_vec.append(city_type[dice_roll])
    else:
        city_type_vec.append("C")

In [7]:
gender_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)  #If coin flip=1(head) if coin flip=0(tail)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(gender)-1)# Rolling the dice if head comes.
        gender_vec.append(gender[dice_roll])
    else:
        gender_vec.append("female")

In [8]:
education_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)  #If coin flip=1(head) if coin flip=0(tail)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(education)-1)# Rolling the dice if head comes.
        education_vec.append(education[dice_roll])
    else:
        education_vec.append("UG")

In [9]:
entity_income_vec=[]
for i in range(50000):
    coin_flip=random.randint(0,1)   #If coin flip=1(head) if coin flip=0(tail)
    if(coin_flip==0):
        dice_roll=random.randint(0,len(EntityIncome)-1)# Rolling the dice if head comes.
        entity_income_vec.append(EntityIncome[dice_roll])
    else:
        entity_income_vec.append("10000")

In [10]:
avg_vec=[]
for i in range(50000):
        if(city_type_vec[i]== "A"):
            avg_vec.append(15000)
        elif (city_type_vec[i]=="D"):
            avg_vec.append(2500)
        elif (city_type_vec[i]=="C"):
            avg_vec.append(5000)
        else:
            avg_vec.append(10000)

In [11]:
#For EntityFamilyIncome column if the number of dependents are 0 then the Entityfamilyincome == EntiyIncome this case is taken care of.

entity_family_income_vec=[]

for i in range(50000):
    if(Dependents_vec[i]>0):
        entity_family_income_vec.append(int(entity_income_vec[i])+random.randint(10000,100000))
    else:
        entity_family_income_vec.append(entity_income_vec[i])


In [12]:
DataSet = pd.DataFrame()
DataSet["Entity_ID"] = entity_id
DataSet["City"] = city_type_vec
DataSet["Marital Status"] = marital_vec
DataSet["Education"] = education_vec
DataSet["Gender"] =gender_vec
DataSet["Dependencies"]=Dependents_vec
DataSet["Entity's Income"]=entity_income_vec
DataSet["Entity's Family Income"]= entity_family_income_vec
DataSet["Average Expenditure per Entity per Month"]= avg_vec

DataSet

Entity_ID City Marital Status     Education  Gender  Dependencies  \
0              0    C        married  Not educated    male             2   
1              1    C        married            UG    male             2   
2              2    C      unmarried            UG  female             2   
3              3    C        married            UG  female             2   
4              4    C        married            UG  female             3   
5              5    A        married            UG  female             2   
6              6    C        married            UG  female             4   
7              7    C      unmarried            UG  female             1   
8              8    D        married            UG  female             2   
9              9    C      unmarried            UG  female             2   
10            10    C        married            UG  female             2   
11            11    C        married            UG  female             2   
12            12    A        married            UG  female             2   
13            13    B        married  Not educated    male             2   
14            14    D        married            UG  female             3   
15            15    A        married            PG  female             2   
16            16    D      unmarried            PG    male             3   
17            17    C        married          Ph.d  female             2   
18            18    D        married          Ph.d    male             2   
19            19    C      unmarried            UG  female             2   
20            20    C        married            UG  female             2   
21            21    C        married            UG    male             2   
22            22    C        married            UG  female             2   
23            23    C        married  Not educated  female             2   
24            24    A        married            UG  female             2   
25            25    C        married          Ph.d    male             2   
26            26    D        married            PG  female             0   
27            27    D      unmarried  Not educated  female             2   
28            28    C      unmarried            UG  female             3   
29            29    D        married            UG    male             4   
...          ...  ...            ...           ...     ...           ...   
49970      49970    B      unmarried          Ph.d    male             2   
49971      49971    C        married            UG  female             1   
49972      49972    C        married            PG  female             2   
49973      49973    C        married            UG  female             4   
49974      49974    C        married            UG    male             1   
49975      49975    C        married            UG  female             2   
49976      49976    C        married            UG    male             2   
49977      49977    C        married          Ph.d  female             4   
49978      49978    C        married            UG  female             0   
49979      49979    C        married            UG  female             0   
49980      49980    D      unmarried          Ph.d  female             2   
49981      49981    C        married            UG  female             2   
49982      49982    C        married            UG    male             2   
49983      49983    B        married  Not educated  female             2   
49984      49984    A        married            UG  female             2   
49985      49985    C        married            PG  female             3   
49986      49986    C        married            UG  female             4   
49987      49987    C        married            UG    male             3   
49988      49988    A        married            UG    male             2   
49989      49989    A        married            UG  female             2   
49990      49990    C        married            UG  fem

In [13]:
### QUERIES

In [14]:
# QUERY A IS DONE AFTER QUERY O.

In [15]:
#  B. Number of Families countif the number of dependents are >0

Dependents_greater_0=((DataSet['Dependencies']>0).tolist()).count(1)
print("Number of Families with dependents are greater than 0 ==>",Dependents_greater_0)

Number of Families with dependents are greater than 0 ==> 44838


In [16]:
# C. Number of Single and Married Entities

Married=DataSet['Marital Status'].tolist().count('married')
Unmarried=DataSet['Marital Status'].tolist().count('unmarried')
print("Number of Married Entity==>" ,Married)
print("Number of UnMarried Entity==>", Unmarried)

Number of Married Entity==> 37553
Number of UnMarried Entity==> 12447


In [17]:
#  D. Entity: Average Income

DataSet["Entity's Income"].astype(int).mean()

503093.2

In [18]:
# E. Entity: Average Family Income
DataSet["Entity's Family Income"].astype(int).mean()

552387.3877

In [19]:
# F. Number of Single and Married Entities

Married=DataSet['Marital Status'].tolist().count('married')
Unmarried=DataSet['Marital Status'].tolist().count('unmarried')
print("Number of Married Entity==>" ,Married)
print("Number of UnMarried Entity==>", Unmarried)

Number of Married Entity==> 37553
Number of UnMarried Entity==> 12447


In [20]:
# G. How many entities are Educated and Uneducated ?

Uneducated=(DataSet['Education']).tolist().count("Not educated")
Educated=((DataSet['Education']).tolist().count('UG')+(DataSet['Education']).tolist().count('PG')+(DataSet['Education']).tolist().count('Ph.d'))
print("Number of Uneducated Entity==>",Educated)
print("Number of Uneducated Entity==>",Uneducated)

Number of Uneducated Entity==> 43665
Number of Uneducated Entity==> 6335


In [21]:
# H. How many Entities at the end of the year can make savings financially ?
savings_vec=[]
for i in range(50000):
    savings=(int(entity_income_vec[i])-int(avg_vec[i]))
    savings_vec.append(savings)
                                    
# DataSet["Savings"] = DataSet["Entity's Income"] - DataSet["Average Expenditure per Entity per Month"]
DataSet["Savings"]=savings_vec
Savings=((DataSet['Savings']>0).tolist()).count(1)
print("Number of Entities that can make Savings==>" ,Savings)

Number of Entities that can make Savings==> 43710


In [22]:
# I. How many Entities at the end of the year are break even financially ?
BreakEven=((DataSet['Savings']==0).tolist()).count(1)
print("Number of Financially broken entity ==>", BreakEven)


Number of Financially broken entity ==> 3176


In [23]:
# J.How many Entities at the end of the year may need loan financially ?

LoanNeed=((DataSet['Savings']<0).tolist()).count(1)
print("Number of entity require loan at end of year ==>",LoanNeed)

Number of entity require loan at end of year ==> 3114


In [24]:
# K.How many Entities can afford  car loans ?

CarLoan=((DataSet['Savings']>10000).tolist()).count(1)
print("Number of entity require carloan at end of year",CarLoan)

Number of entity require carloan at end of year 24774


In [25]:
# L. How many Entities can afford Home Loans ?

HouseLoan=((DataSet['Savings']>20000).tolist()).count(1)
print("Number of entity require homeloan at end of year",HouseLoan)


Number of entity require homeloan at end of year 24642


In [26]:
# M. How many Entities can be advised on Savings and Loans ?
Advised=((DataSet['Savings']<2000).tolist()).count(1)
print("Number of entities can be advised on Savings and Loans",Advised)

Number of entities can be advised on Savings and Loans 6290


In [27]:
DataSet

Entity_ID City Marital Status     Education  Gender  Dependencies  \
0              0    C        married  Not educated    male             2   
1              1    C        married            UG    male             2   
2              2    C      unmarried            UG  female             2   
3              3    C        married            UG  female             2   
4              4    C        married            UG  female             3   
5              5    A        married            UG  female             2   
6              6    C        married            UG  female             4   
7              7    C      unmarried            UG  female             1   
8              8    D        married            UG  female             2   
9              9    C      unmarried            UG  female             2   
10            10    C        married            UG  female             2   
11            11    C        married            UG  female             2   
12            12    A        married            UG  female             2   
13            13    B        married  Not educated    male             2   
14            14    D        married            UG  female             3   
15            15    A        married            PG  female             2   
16            16    D      unmarried            PG    male             3   
17            17    C        married          Ph.d  female             2   
18            18    D        married          Ph.d    male             2   
19            19    C      unmarried            UG  female             2   
20            20    C        married            UG  female             2   
21            21    C        married            UG    male             2   
22            22    C        married            UG  female             2   
23            23    C        married  Not educated  female             2   
24            24    A        married            UG  female             2   
25            25    C        married          Ph.d    male             2   
26            26    D        married            PG  female             0   
27            27    D      unmarried  Not educated  female             2   
28            28    C      unmarried            UG  female             3   
29            29    D        married            UG    male             4   
...          ...  ...            ...           ...     ...           ...   
49970      49970    B      unmarried          Ph.d    male             2   
49971      49971    C        married            UG  female             1   
49972      49972    C        married            PG  female             2   
49973      49973    C        married            UG  female             4   
49974      49974    C        married            UG    male             1   
49975      49975    C        married            UG  female             2   
49976      49976    C        married            UG    male             2   
49977      49977    C        married          Ph.d  female             4   
49978      49978    C        married            UG  female             0   
49979      49979    C        married            UG  female             0   
49980      49980    D      unmarried          Ph.d  female             2   
49981      49981    C        married            UG  female             2   
49982      49982    C        married            UG    male             2   
49983      49983    B        married  Not educated  female             2   
49984      49984    A        married            UG  female             2   
49985      49985    C        married            PG  female             3   
49986      49986    C        married            UG  female             4   
49987      49987    C        married            UG    male             3   
49988      49988    A        married            UG    male             2   
49989      49989    A        married            UG  female             2   
49990      49990    C        married            UG  fem

In [28]:
# N. Categorize every entity_id economic status as [ Excellent, Good, Moderate, Average, Poor ]

avg_income_vec=[]

for i in range(50000):
    j=random.randint(0,1)
    income=(int(entity_income_vec[i])+int(entity_family_income_vec[i]))
    avg_income_vec.append(income)
                                                       
economic_status_vec=[]   
label_status_vec=[]
for i in range(50000):
    if(avg_income_vec[i] >=900000):
            economic_status_vec.append("Excellent")
            label_status_vec.append(0)
    elif(avg_income_vec[i] >400000 and avg_income_vec[i] < 900000 ):
            economic_status_vec.append("Good")
            label_status_vec.append(1)
    elif(avg_income_vec[i] > 100000 and avg_income_vec[i] <= 400000):
            economic_status_vec.append("Moderate")
            label_status_vec.append(2)
    elif(avg_income_vec[i] >25000 and avg_income_vec[i] <= 100000):
            economic_status_vec.append("Average")    
            label_status_vec.append(3)
    else:
            economic_status_vec.append("Poor") 
            label_status_vec.append(4)

In [29]:
DataSet = pd.DataFrame()
DataSet["Entity_ID"] = entity_id
DataSet["City"] = city_type_vec
DataSet["Marital Status"] = marital_vec
DataSet["Education"] = education_vec
DataSet["Gender"] =gender_vec
DataSet["Dependencies"]=Dependents_vec
DataSet["Entity's Income"]=entity_income_vec
DataSet["Entity's Family Income"]= entity_family_income_vec
DataSet["Average Expenditure per Entity per Month"]= avg_vec
DataSet["Total Income of Entity's Family"] = avg_income_vec
DataSet["Economic Status"]= economic_status_vec
DataSet["Label"]=label_status_vec
DataSet

Entity_ID City Marital Status     Education  Gender  Dependencies  \
0              0    C        married  Not educated    male             2   
1              1    C        married            UG    male             2   
2              2    C      unmarried            UG  female             2   
3              3    C        married            UG  female             2   
4              4    C        married            UG  female             3   
5              5    A        married            UG  female             2   
6              6    C        married            UG  female             4   
7              7    C      unmarried            UG  female             1   
8              8    D        married            UG  female             2   
9              9    C      unmarried            UG  female             2   
10            10    C        married            UG  female             2   
11            11    C        married            UG  female             2   
12            12    A        married            UG  female             2   
13            13    B        married  Not educated    male             2   
14            14    D        married            UG  female             3   
15            15    A        married            PG  female             2   
16            16    D      unmarried            PG    male             3   
17            17    C        married          Ph.d  female             2   
18            18    D        married          Ph.d    male             2   
19            19    C      unmarried            UG  female             2   
20            20    C        married            UG  female             2   
21            21    C        married            UG    male             2   
22            22    C        married            UG  female             2   
23            23    C        married  Not educated  female             2   
24            24    A        married            UG  female             2   
25            25    C        married          Ph.d    male             2   
26            26    D        married            PG  female             0   
27            27    D      unmarried  Not educated  female             2   
28            28    C      unmarried            UG  female             3   
29            29    D        married            UG    male             4   
...          ...  ...            ...           ...     ...           ...   
49970      49970    B      unmarried          Ph.d    male             2   
49971      49971    C        married            UG  female             1   
49972      49972    C        married            PG  female             2   
49973      49973    C        married            UG  female             4   
49974      49974    C        married            UG    male             1   
49975      49975    C        married            UG  female             2   
49976      49976    C        married            UG    male             2   
49977      49977    C        married          Ph.d  female             4   
49978      49978    C        married            UG  female             0   
49979      49979    C        married            UG  female             0   
49980      49980    D      unmarried          Ph.d  female             2   
49981      49981    C        married            UG  female             2   
49982      49982    C        married            UG    male             2   
49983      49983    B        married  Not educated  female             2   
49984      49984    A        married            UG  female             2   
49985      49985    C        married            PG  female             3   
49986      49986    C        married            UG  female             4   
49987      49987    C        married            UG    male             3   
49988      49988    A        married            UG    male             2   
49989      49989    A        married            UG  female             2   
49990      49990    C        married            UG  fem

In [30]:
# O. Build a prediction model to find the new entity’s Economic status  

temp=DataSet
# Import LabelEncoder
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X=["Entity_ID","City","Marital Status","Education","Gender","Dependencies","Entity\'s Income","Entity\'s Family Income","Average Expenditure per Entity per Month","Total Income of Entity\'s Family"]
Y=["Label"]


le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
temp['Average Expenditure per Entity per Month']=le.fit_transform(temp['Average Expenditure per Entity per Month'])
temp['Gender']=le.fit_transform(temp['Gender'])
temp['Education']=le.fit_transform(temp['Education'])
temp['Marital Status']=le.fit_transform(temp['Marital Status'])
temp['City']=le.fit_transform(temp['City'])

X=temp[X]
Y=temp[Y]

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)


# instantiate the model 
Log_Regression = LogisticRegression(C=10, solver='newton-cg', multi_class='multinomial')

# fit the model with data
Log_Regression.fit(X_train,Y_train)
Y_pred=Log_Regression.predict(X_test)



C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [31]:


# A. What is the typical shape of the training and testing data ?

print("SIZE OF TRAINING DATASET==>",X_train.size)
print("SIZE OF TESTING DATASET==>",X_test.size)
print("SHAPE OF TRAINING DATASET==>",X_train.shape)
print("SHAPE OF TESTING DATASET==>",X_test.shape)

SIZE OF TRAINING DATASET==> 400000
SIZE OF TESTING DATASET==> 100000
SHAPE OF TRAINING DATASET==> (40000, 10)
SHAPE OF TESTING DATASET==> (10000, 10)


In [32]:

#  P. Perform metric level analysis of the model


from sklearn import metrics

Confusion_Matrix = metrics.confusion_matrix(Y_test, Y_pred)
print(Confusion_Matrix)

FP = Confusion_Matrix .sum(axis=0) - np.diag(Confusion_Matrix )
FN = Confusion_Matrix .sum(axis=1) - np.diag(Confusion_Matrix )
TP = np.diag(Confusion_Matrix)
TN = Confusion_Matrix .sum() - (FP + FN + TP)
from sklearn.metrics import confusion_matrix
import numpy as np


Accuracy=sum(np.diag(Confusion_Matrix ))/ np.sum(Confusion_Matrix )
print("Accuracy in %= ",Accuracy*100)

[[3913   45    0    0    0]
 [  93  483   37    0    0]
 [   0   95 1121  142    4]
 [   0    0  120 3416    6]
 [   0    0    0   16  509]]
Accuracy in %=  94.42


In [33]:
print("Model Evaluation Metrics")
print("Total Observations predicted",len(Y_pred))
print("True Positive=>",TP)
print("True Negative=>",TN)
print("False Positive=>",FP)
print("False Negatives=>",FN)
Accuracy = (TP+TN)/len(Y_pred)
print("Accuracy values for the 5 economic classes = ",Accuracy)


Model Evaluation Metrics
Total Observations predicted 10000
True Positive=> [3913  483 1121 3416  509]
True Negative=> [5949 9247 8481 6300 9465]
False Positive=> [ 93 140 157 158  10]
False Negatives=> [ 45 130 241 126  16]
Accuracy values for the 5 economic classes =  [0.9862 0.973  0.9602 0.9716 0.9974]
